### ISSUE TITLE
Getting Stack Trace

### ISSUE THREAD

**Issue by Tjorven-Liebe** [GeyserExtensionists/GeyserUtils#11]
I think, that this prevents GeyserExtensionists/GeyserModelEngine from loading.
Geyser recently updated the behaviour of their Registries on load. https://github.com/GeyserMC/Geyser/commit/8f7a0d0778aa9106ea32527e535fe5d1cc7d7d0d
Maybe that's the issue.

I've tried it on bungeecord (Waterfall) with geyserutils + geysermodelengine in geyser's extensions folder

The stack trace:
[13:51:25 ERROR] [org.geysermc.geyser.event.GeyserEventBus]: An exception occurred while executing event GeyserPostInitializeEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoSuchFieldError: BEDROCK_ENTITY_IDENTIFIERS
        at me.zimzaza4.geyserutils.geyser.GeyserUtils.registerEntityToGeyser(GeyserUtils.java:209) ~[?:?]
        at me.zimzaza4.geyserutils.geyser.GeyserUtils.onEnable(GeyserUtils.java:120) ~[?:?]
        at org.lanternpowered.lmbda.Lmbda$3.accept(Unknown Source) ~[?:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[?:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[?:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[?:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:653) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:271) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:878) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin.onGeyserEnable(GeyserBungeePlugin.java:188) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by zimzaza4** [comment]
did you update your GeyserUtils-Geyser?

**Comment by zimzaza4** [comment]
https://github.com/GeyserExtensionists/GeyserUtils/releases/download/latest/geyserutils-geyser-1.0-SNAPSHOT.jar

**Comment by Tjorven-Liebe** [comment]
To anyone wondering, update your geysermc/geyser to latest version!
