### ISSUE TITLE
[bug] Geyser extension version not loading up

### ISSUE THREAD

**Issue by otDan** [GeyserExtensionists/GeyserUtils#3]
The geyser extension version does not load up on the custom fork geyser standalone build

```
[22:37:00.716 main/ERROR] Couldn't load geyserutils-geyser-1.0-SNAPSHOT.jar in folder /home/minecraft/servers/pokefind-geyser/extensions/geyserutils-geyser-1.0-SNAPSHOT.jar:
java.lang.NoClassDefFoundError: org/geysermc/geyser/skin/SkinProvider$Cape
	at me.zimzaza4.geyserutils.geyser.GeyserUtils.<clinit>(GeyserUtils.java:88) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.load(GeyserExtensionClassLoader.java:57) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadExtension(GeyserExtensionLoader.java:96) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.lambda$loadAllExtensions$0(GeyserExtensionLoader.java:191) ~[Geyser-Standalone.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadAllExtensions(GeyserExtensionLoader.java:158) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.api.extension.ExtensionManager.loadAllExtensions(ExtensionManager.java:88) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionManager.init(GeyserExtensionManager.java:48) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:195) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.GeyserImpl.load(GeyserImpl.java:777) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:225) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:170) [Geyser-Standalone.jar:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.geyser.skin.SkinProvider$Cape
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:107) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.classByName(GeyserExtensionLoader.java:133) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:97) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:79) ~[Geyser-Standalone.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more
```

**Comment by zimzaza4** [comment]
Temporarily use this build
https://github.com/zimzaza4/Geyser/actions/runs/9050743266

**Comment by otDan** [comment]
> Temporarily use this build https://github.com/zimzaza4/Geyser/actions/runs/9050743266

I get a different error after loading with that build:

```
[14:34:06.781 main/ERROR] An exception occurred while executing event  for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.ExceptionInInitializerError: null
	at org.geysermc.geyser.GeyserImpl.provider(GeyserImpl.java:706) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.api.command.Command.builder(Command.java:117) ~[Geyser-Standalone.jar:?]
	at me.zimzaza4.geyserutils.geyser.GeyserUtils.onLoadCommand(GeyserUtils.java:152) ~[?:?]
	at org.lanternpowered.lmbda.Lmbda$5.accept(Unknown Source) ~[Geyser-Standalone.jar:?]
	at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[Geyser-Standalone.jar:?]
	at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Standalone.jar:?]
	at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Standalone.jar:?]
	at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Standalone.jar:?]
	at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) [Geyser-Standalone.jar:?]
	at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.command.GeyserCommandManager.init(GeyserCommandManager.java:105) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:228) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:170) [Geyser-Standalone.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at org.geysermc.geyser.registry.populator.RecipeRegistryPopulator.getCraftingDataFromJsonNode(RecipeRegistryPopulator.java:133) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.populator.RecipeRegistryPopulator.populate(RecipeRegistryPopulator.java:95) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.Registries.<clinit>(Registries.java:204) ~[Geyser-Standalone.jar:?]
	... 14 more
```

**Comment by zimzaza4** [comment]
oh sorry
use this
https://github.com/zimzaza4/Geyser/actions/runs/9064665006

**Comment by otDan** [comment]
> oh sorry use this https://github.com/zimzaza4/Geyser/actions/runs/9064665006
okay this version seems to have loaded up, I still get one error though
```
 java.io.IOException: No such file or directory
         at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
         at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
         at java.base/java.io.File.createNewFile(File.java:1045)
         at me.zimzaza4.geyserutils.geyser.GeyserUtils.loadEntities(GeyserUtils.java:124)
         at me.zimzaza4.geyserutils.geyser.GeyserUtils.onEntitiesDefine(GeyserUtils.java:144)
         at org.lanternpowered.lmbda.Lmbda$4.accept(Unknown Source)
         at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55)
         at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75)
         at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201)
         at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41)
         at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180)
         at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41)
         at org.geysermc.geyser.registry.Registries.callRegistryEvents(Registries.java:244)
         at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:237)
         at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:791)
         at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:230)
         at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194)
         at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:170)
```

**Comment by otDan** [comment]
probably just missing a check if there is anything present? since I had no entities in there the first time

**Comment by zimzaza4** [comment]
please wait a minute
im updating my Geyser fork
and Geyserutils

**Comment by otDan** [comment]
> please wait a minute im updating my Geyser fork and Geyserutils

yeah no worries, just trying to document everything so you don't need to debug too much

**Comment by zimzaza4** [comment]
ok,
now use
https://github.com/zimzaza4/Geyser/actions/runs/9226397237 (latest actions build)

https://github.com/zimzaza4/GeyserUtils/releases/download/custom-entity-1.0/geyserutils-geyser-1.0-SNAPSHOT.jar
